### ISSUE TITLE
Choose a crate/library for interacting with the Docker daemon

### ISSUE THREAD

**Issue by harlem88** [joshuachp/dockrs#3]
Prepare two different pull request to show the difference between:
- https://crates.io/crates/bollard
- https://crates.io/crates/shiplift

Focusing on :
- coverage of Docker Engine API
- simplicity of API to use
- crate/repo maintenance ( Actively Developed / Maintained )
....

**Comment by joshuachp** [comment]
The two crates have the same in scope and features, but I think the one we should use is `bollard` since the interface seems nicer to work with.  

They have a similar structure and code, since they are based on the same API, so it's hard to find points against one or the other.

Although  `shiplift` has a simpler interface, the biggest hurdle I had trying it was that the Container struct keeps a reference to the Docker struct for the Transport object. In the other one, the transport is wrapped in an Arc, so it's easier to pass around. 

This isn't a big difference, since most of the work is still done upfront. But I think it can make things easier if we start to pass those objects around.

You can see an example of creating and running a container in the following PR for both libraries: 

- #6 
- #7

**Comment by harlem88** [comment]
- Bollard  is also actively developed / maintained , last release  [v.0.14.0 - Jan 21, 2023](https://github.com/fussybeaver/bollard/releases/tag/v0.14.0).
 - Shiplift last release  [v0.7.0 - Feb 21, 2021](https://github.com/softprops/shiplift/releases/tag/v0.7.0)

**Comment by harlem88** [comment]
I vote for `Bollard`, What do you think @FrancescoVaiani @sorru94 ?
